membership: list child and parent groups
giolekva/pcloud pull request #107
Opened 2024-03-20 19:01 UTC by DTabidze

2024-03-20 19:32 UTC, giolekva requested changes

2024-03-20 19:32 UTC, giolekva commented on core/auth/memberships/main.go
> +	GetParentGroups(group string, allGroups map[string]bool) error
This should return `[]string, error` and `allGroups` should not be an argument

2024-03-20 19:32 UTC, giolekva commented on core/auth/memberships/main.go
> +	GetParentGroups(group string, allGroups map[string]bool) error
Rename to `GetAllTransitiveGroupsForGroup` similar to like we have it named for users.

2024-03-21 10:21 UTC, DTabidze commented on core/auth/memberships/main.go
> +	GetParentGroups(group string, allGroups map[string]bool) error
Probably Fixed.

2024-03-21 10:38 UTC, giolekva requested changes

2024-03-21 10:38 UTC, giolekva commented on core/auth/memberships/main.go
> +	GetParentGroups(group string, allGroups map[string]bool) error
`GetAllTransitiveGroupsForGroup` not `GetAllParent..`

2024-03-21 10:38 UTC, giolekva commented on core/auth/memberships/main.go
> +	}
For each group individually querying description will be really slow, change `GetAllTransitiveGroupsForGroup` so that it returns `([]Group, error)`. That way you won't have to query for descriptions separately

2024-03-21 10:38 UTC, giolekva commented on core/auth/memberships/main.go
> +	}
Same here, if you need descriptions of children groups change `GetDirectChildrenGroups` to include descriptions in the return value.

2024-03-21 10:38 UTC, giolekva commented on core/auth/memberships/main.go
> +		ParentGroups    []Group
Rename this to `TransitiveGroups` so it is clear that it includes not only direct parent groups.

2024-03-21 12:30 UTC, DTabidze commented on core/auth/memberships/main.go
> +		ParentGroups    []Group
Done.

2024-03-21 12:30 UTC, DTabidze commented on core/auth/memberships/main.go
> +	}
Done.

2024-03-21 12:30 UTC, DTabidze commented on core/auth/memberships/main.go
> +	}
Done.

2024-03-21 14:22 UTC, giolekva requested changes

2024-03-21 14:22 UTC, giolekva commented on core/auth/memberships/main.go
> +	}
You can improve performance with a little bit of change. Consider example:
`X > A`
`X > B`
`A > user`
`B > user`
`a,b,c,d,e,f,g > X`

With current implementation you'll call `GetAlLTransitiveGroupsForGroup(A)` and `GetAlLTransitiveGroupsForGroup(B)` separately, so `a` `b` `c`, ... and other lowercased groups will be visited twice recursively.

If instead you call `getAllParentGroupsRecursive(A, map)` and `getAllParentGroupsRecursive(B, sameMap)` all groups will be visited only once.

2024-03-21 14:22 UTC, giolekva commented on core/auth/memberships/main.go
> +	}
The fact that you need this logic here means that there is a bug in `GetAllTransitiveGroupsForGroup` method implementation. It should not include group you pass as an argument in the result, meaning if `A > B` and you call that method it should return `[A]` only and not `[A, B]`.

Fix `GetAllTransitiveGroupsForGroup ` method so it does not return group it was called on.

2024-03-21 14:50 UTC, DTabidze commented on core/auth/memberships/main.go
> +	}
Done.

2024-03-21 14:50 UTC, DTabidze commented on core/auth/memberships/main.go
> +	}
Done.

2024-03-21 16:13 UTC, giolekva requested changes

2024-03-21 16:13 UTC, giolekva commented on core/auth/memberships/main.go
> +	parentGroups, err := s.GetAllTransitiveGroupsForGroup(parentGroup)
Why did you change argument type from `string` to `Group`? Now client has to create fake group to be able to query parents by name.

2024-03-21 16:13 UTC, giolekva commented on core/auth/memberships/main.go
>  	var allTransitiveGroups []Group
Move this definition closer to where it actually is used first time, line 342

2024-03-21 16:13 UTC, giolekva commented on core/auth/memberships/main.go
> +	allGroups := make(map[Group]bool)
nit: I'd rename `allGroups` to `visitedGroups`. All means all of the groups while visited means just the ones you touched while doing recursion.

Here and in other similar places.

2024-03-21 19:36 UTC, DTabidze commented on core/auth/memberships/main.go
> +	parentGroups, err := s.GetAllTransitiveGroupsForGroup(parentGroup)
I might be wrong but, inside GetAllTransitiveGroupsForGroup func i call recursive func getAllParentGroupsRecursive, and i need to invoke it with Group struct, if i won't do that I don't know how to save Names and Descriptions simultaneously. Also i used same approach on line 583-584:
	group := Group{Name: groupName, Description: description}
	transitiveGroups, err := s.store.GetAllTransitiveGroupsForGroup(group)
it's just I already had a Description there, could query and use real description for this one also.

2024-03-21 19:36 UTC, DTabidze commented on core/auth/memberships/main.go
>  	var allTransitiveGroups []Group
Done.

2024-03-21 19:36 UTC, DTabidze commented on core/auth/memberships/main.go
> +	allGroups := make(map[Group]bool)
Nice feedback. DOne.

2024-03-21 21:44 UTC, DTabidze commented on core/auth/memberships/main.go
> +	parentGroups, err := s.GetAllTransitiveGroupsForGroup(parentGroup)
Done.

2024-03-22 07:06 UTC, giolekva requested changes

2024-03-22 07:06 UTC, giolekva commented on core/auth/memberships/main.go
> +	initialGroup := Group{Name: group}
This will cause a bug, let's say we have to groups:
`name: A description: aaa`
`name: B description: bbb`
And we have bidirectional relationship between these two groups: `A > B` and `B > A` (forget the fact that cycles are not allowed, look at this code just from purely implementation standpoint)
At the end `visitedGroups` map will look like
```go
map[Group]bool{
  {Name: "A"}: true,
  {Name: "B", Description: "bbb"}: true,
  {Name: "A", Description: "aaa"}: true,
}
```

Repeating group `A` twice. This is again caused by the fact that `getAllParentGroupsRecursive` takes `Group` as an argument and `visitedGroups` uses `Group` as a key. Change `visitedGroups` to `map[string]Group`.

This would be caught by unit tests, maybe we should start writing them. Ping me so I can show you how.

2024-03-22 07:06 UTC, giolekva commented on core/auth/memberships/main.go
> +	parentGroups, err := s.GetAllTransitiveGroupsForGroup(parentGroup)
`map[string]Group`

2024-03-22 07:41 UTC, giolekva commented on core/auth/memberships/main.go
> +	initialGroup := Group{Name: group}
Added unit test to check this and it is failing. PTAL at `store_test.go` and add couple other tests covering other methods.

2024-03-22 13:13 UTC, giolekva approved these changes

2024-03-22 13:25 UTC, merged