memberships: remove owner, member and child group
giolekva/pcloud pull request #128
Opened 2024-03-26 13:38 UTC by DTabidze

2024-03-26 14:33 UTC, giolekva requested changes
nice

2024-03-26 14:33 UTC, giolekva commented on core/auth/memberships/main.go
> +		}
Is this part needed? If any of the groups does not exist, pair of (parent, child) won't exist either so store.RemoveFromGroupToGroup invocation will fail as well.

2024-03-26 14:33 UTC, giolekva commented on core/auth/memberships/group.html
> +                    <input type="hidden" name="child-group" value="{{ .Name }}">
I think this is not used

2024-03-26 14:33 UTC, giolekva commented on core/auth/memberships/group.html
> +                <form action="/remove-child-group/{{ $parentGroupName }}/{{ .Name }}" method="post" onsubmit="return confirm('Are you sure you want to remove this group as child?')">
Let's do same for owners and members as well.

2024-03-26 15:40 UTC, giolekva requested changes

2024-03-26 15:40 UTC, giolekva commented on core/auth/memberships/group.html
> +                    <input type="hidden" name="table-name" value="owners">
API should be clean, and table name is an internal detail of our current implementation which should not be expose externally.

It is cleaner and more secure to have separate endpoints `/remove-member` and `/remove-owner`

2024-03-26 15:40 UTC, giolekva commented on core/auth/memberships/group.html
> +                <form action="/remove-user-group/{{ . }}/{{ $parentGroupName }}" method="post" onsubmit="return confirm('Are you sure you want to remove this user from group?')">
Here you are revoking ownership of the group, while error message talks about just removing user from the group.
Change message to `Are you sure you want to revoke user {{ მომხმარებელი }} ownership of the {{ ჯგუფის სახელი }} group?`

2024-03-26 15:40 UTC, giolekva commented on core/auth/memberships/group.html
> +                <form action="/remove-user-group/{{ . }}/{{ $parentGroupName }}" method="post" onsubmit="return confirm('Are you sure you want to remove this user from group?')">
Include user and group names in confirmation dialog

2024-03-26 15:40 UTC, giolekva commented on core/auth/memberships/group.html
> +                    <input type="hidden" name="table-name" value="user_to_group">
remove table-name from here as well.

2024-03-26 16:30 UTC, DTabidze commented on core/auth/memberships/group.html
> +                <form action="/remove-user-group/{{ . }}/{{ $parentGroupName }}" method="post" onsubmit="return confirm('Are you sure you want to remove this user from group?')">
Done.

2024-03-26 16:30 UTC, DTabidze commented on core/auth/memberships/group.html
> +                    <input type="hidden" name="table-name" value="owners">
Done.

2024-03-26 16:30 UTC, DTabidze commented on core/auth/memberships/group.html
> +                <form action="/remove-user-group/{{ . }}/{{ $parentGroupName }}" method="post" onsubmit="return confirm('Are you sure you want to remove this user from group?')">
Done.

2024-03-26 16:30 UTC, DTabidze commented on core/auth/memberships/group.html
> +                    <input type="hidden" name="table-name" value="user_to_group">
Done.

2024-03-27 04:19 UTC, giolekva requested changes

2024-03-27 04:19 UTC, giolekva commented on core/auth/memberships/group.html
> +                <form action="/remove-group-owner/{{ . }}/{{ $parentGroupName }}" method="post" onsubmit="return confirm('Are you sure you want to revoke user {{ . }} ownership of the {{ $parentGroup
Logically group name should come first and then the owner

2024-03-27 04:19 UTC, giolekva commented on core/auth/memberships/group.html
> +                <form action="/remove-group-member/{{ . }}/{{ $parentGroupName }}" method="post" onsubmit="return confirm('Are you sure you want to remove user {{ . }} user from {{ $parentGroupName }
Same here, put group name first in the url

2024-03-27 04:19 UTC, giolekva commented on core/auth/memberships/main.go
> +		r.HandleFunc("/{action}/{username}/{group-name}", s.removeUserFromGroupHandler)
Theoretically this has a chance of matching other unintended url. If you really want to reuse the handler for these two endpoints, `/remove-{action}/{username}/{group-name}` is safer to use

2024-03-27 09:20 UTC, DTabidze commented on core/auth/memberships/group.html
> +                <form action="/remove-group-owner/{{ . }}/{{ $parentGroupName }}" method="post" onsubmit="return confirm('Are you sure you want to revoke user {{ . }} ownership of the {{ $parentGroup
Done.

2024-03-27 09:20 UTC, DTabidze commented on core/auth/memberships/group.html
> +                <form action="/remove-group-member/{{ . }}/{{ $parentGroupName }}" method="post" onsubmit="return confirm('Are you sure you want to remove user {{ . }} user from {{ $parentGroupName }
Done.

2024-03-27 09:20 UTC, DTabidze commented on core/auth/memberships/main.go
> +		r.HandleFunc("/{action}/{username}/{group-name}", s.removeUserFromGroupHandler)
Done.

2024-03-27 09:22 UTC, giolekva approved these changes

2024-03-27 09:25 UTC, merged