Login service
giolekva/pcloud pull request #51
Opened 2021-04-16 17:31 UTC by iomodo

This PR adds a login service

2021-04-17 17:10 UTC, bakurits commented on core/kg/app/user.go
> +		return user, nil
No need to check password when authenticating with ID?

2021-04-20 20:34 UTC, iomodo commented on core/kg/app/user.go
> +		return user, nil
good catch @bakurits

2021-04-29 19:48 UTC, giolekva requested changes
Unit tests? :(

2021-04-29 19:48 UTC, giolekva commented on core/kg/common/utils.go
> +var encoding = base32.NewEncoding("ybndrfg8ejkmcpqxot1uwisza345h769")
Where does this string come from?

2021-04-29 19:48 UTC, giolekva commented on core/kg/common/utils.go
> +package common
I strongly discourage use of files like utils/commons and so on.
Over time they tend to accumulate completely unrelated set of functions and becomes hard to read.

Can you split It into separate libs? Sth like: id.go encoding.go time.go ... you decide on exact granularity to split

2021-04-29 19:48 UTC, giolekva commented on core/kg/common/utils.go
> +		return make(map[string]string)
Using this in production does not seem safe.
Why swallow/hide the error?

2021-04-29 19:48 UTC, giolekva commented on core/kg/common/interfaces.go
> +	AuthenticateUserForLogin(userID, loginID, password string) (*model.User, error)
In what circumstances would we need to support authenticating users by their userID and not username?
From my understanding userID should be internal to the system.

2021-04-29 19:48 UTC, giolekva commented on core/kg/app/user.go
> +
rm extra empty line

2021-04-29 19:48 UTC, giolekva commented on core/kg/app/user.go
> +		return nil, errors.Wrapf(err, "login error")
"login error" seams too generic, how about using "invalid credentials" ?

2021-04-29 19:48 UTC, giolekva commented on core/kg/model/role.go
> +	if strings.TrimLeft(r.Name, "abcdefghijklmnopqrstuvwxyz0123456789_") != "" {
Create a RoleNameAllowedChars const string from "abide...." ?

2021-04-29 19:48 UTC, giolekva commented on core/kg/model/role.go
> +
rm extra empty lines, here and bellow

2021-04-29 19:48 UTC, giolekva commented on core/kg/model/permission.go
> +
rm empty line

2021-04-29 19:48 UTC, giolekva commented on core/kg/model/role.go
> +	check := func(perms []*Permission, permission string) bool {
How about creating AllPermissionIds const field next to AllPermissions in permission.go so we don't have to do a linear search here?

2021-04-29 19:48 UTC, giolekva commented on core/kg/model/errors.go
> +	ErrForbidden    = errors.New("forbidden")
What is the difference between access denied and forbidden?

2021-04-29 19:48 UTC, giolekva commented on core/kg/store/sqlstore/session_store.go
> +	ss.db.MustExec(schema)
Does squirrel always run CREATE TABLE IF ... on every query?
First time I'm seeing such pattern

2023-12-25 15:29 UTC, closed without merging