Basic in memory implementation of network Manager
giolekva/pcloud pull request #53
Opened 2021-05-01 16:06 UTC by giolekva

This PR introduces two new interfaces with their basic implementations:
* Manager: responsible for maintaining the full network configuration across one PCloud instance
* InMemoryManager: keeps all information in memory
* IPManager: responsible for generating new IP addresses
* SequentialIPManager: generates continuous IP addresses

Next steps:
* Wrap InMemoryManager to add persistence
* Extend IPManager so it can keep track of no-longer used IP addresses, needed for safety so old IP addresses which were attached to now removed devices are not re-used in future.

2021-05-06 19:55 UTC, iomodo requested changes

2021-05-06 19:55 UTC, iomodo commented on core/vpn/manager.go
> +	// Returns network configuration for a device with give public key.
```suggestion
	// Returns network configuration for a device with a given public key.
```

2021-05-06 19:55 UTC, iomodo commented on core/vpn/manager.go
> +	GetNetworkMap(pubKey types.PublicKey) (*types.NetworkMap, error)
Shouldn't encryption be the part of this method?

2021-05-06 19:55 UTC, iomodo commented on core/vpn/manager.go
> +	AddNetworkMapChangeCallback(pubKey types.PublicKey, cb NetworkMapChangeCallback) error
Should the networkMap passed in `NetworkMapChangeCallback` be encrypted as well?

2021-05-06 19:55 UTC, iomodo commented on core/vpn/ip_manager_test.go
> +	if ipA.String() != "10.0.0.1" {
`assert.Equalf`?

2021-05-06 19:55 UTC, iomodo commented on core/vpn/in_memory_manager.go
> +func NewInMemoryManager(ipm IPManager) Manager {
Should `vpn` use `kg` to store this?

2021-05-06 19:55 UTC, iomodo commented on core/vpn/in_memory_manager.go
> +	delete(m.keyToDevices, pubKey) // TODO(giolekva): maybe mark as deleted?
no need for marking in the inmemory implementation. DB will do that

2021-05-06 19:55 UTC, iomodo commented on core/vpn/ip_manager.go
> +	keyToIP map[types.PublicKey]netaddr.IP
Should this be only in memory?

2021-05-06 19:55 UTC, iomodo commented on core/vpn/in_memory_manager.go
> +		panic(err)
Returning an error might be better. What happens when the reason of the error is not that `New` was not called but a DB connection or whatnot? Should we panic then too?

2021-05-06 19:55 UTC, iomodo commented on core/vpn/in_memory_manager_test.go
> +func TestTwoPeers(t *testing.T) {
ditto regarding `assert.XXX`

2021-05-09 09:12 UTC, giolekva commented on core/vpn/in_memory_manager.go
> +func NewInMemoryManager(ipm IPManager) Manager {
Yes, next PR will refactor this code and move data storage layer into Store interface backed with kg.
Manager will keep logic purely around generating network configurations.

2021-05-14 17:55 UTC, giolekva commented on core/vpn/in_memory_manager_test.go
> +func TestTwoPeers(t *testing.T) {
see my comment above

2021-05-14 17:55 UTC, giolekva commented on core/vpn/ip_manager.go
> +	keyToIP map[types.PublicKey]netaddr.IP
As per PR description, persistence is coming in followup changes.

2021-06-02 15:31 UTC, giolekva commented
ping

2021-06-20 10:27 UTC, merged