Username Error handling. FormData save.
giolekva/pcloud pull request #75
Opened 2024-02-16 14:33 UTC by DTabidze

2024-02-18 09:05 UTC, giolekva requested changes

2024-02-18 09:05 UTC, giolekva commented on core/installer/welcome/welcome.go
> +	if err := r.ParseForm(); err == nil {
This handler processes only `GET` requests, so there is no form submitted by the user at this point. We are simply rendering the form. So form data (`previousFormData`) will always be empty.

2024-02-18 09:05 UTC, giolekva commented on core/installer/welcome/welcome.go
> +func renderErrorMessage(w http.ResponseWriter, errorMessage string, formData createAccountReq) {
Rename to `renderForm` or `renderRegistrationForm`

2024-02-18 09:05 UTC, giolekva commented on core/installer/welcome/welcome.go
> +			// TODO rendering etc
What is this TODO about?

2024-02-18 09:05 UTC, giolekva commented on core/installer/welcome/welcome.go
> +			fmt.Println(respStr)
Remove debug line

2024-02-19 14:22 UTC, DTabidze commented on core/installer/Makefile
> +	docker build --file=Dockerfile.flux --tag=dtabidze/flux:latest . --platform=linux/arm64
Done

2024-02-19 14:22 UTC, DTabidze commented on core/auth/ui/Makefile
> +	docker build --platform linux/arm64 --tag=dtabidze/auth-ui:arm64 .
Done

2024-02-19 14:45 UTC, DTabidze commented on core/installer/welcome/welcome.go
> +			// TODO rendering etc
Done

2024-02-19 14:46 UTC, DTabidze commented on core/auth/ui/api.go
> +func handleIdentityCreateError(w http.ResponseWriter, resp *http.Response) {
Done

2024-02-19 14:47 UTC, DTabidze commented on core/installer/welcome/welcome.go
> +func renderErrorMessage(w http.ResponseWriter, errorMessage string, formData createAccountReq) {
Done

2024-02-19 14:48 UTC, DTabidze commented on core/installer/welcome/welcome.go
> +			fmt.Println(respStr)
Done

2024-02-19 14:48 UTC, DTabidze commented on core/auth/ui/api.go
> +	//
Done

2024-02-19 15:12 UTC, DTabidze commented on core/installer/welcome/welcome.go
> +	if err := r.ParseForm(); err == nil {
Done

2024-02-22 06:49 UTC, giolekva approved these changes
Looks good.

One side note: it should be PR reviewer who marks comments as resolved, not the author.
Feel free to merge. You can do stylistic improvements in the follow up PR

2024-02-22 06:49 UTC, giolekva commented on core/auth/ui/api.go
> +func handleIdentityCreateError(errResp ErrorResponse) string {
rename to `extractErrorMessage`

2024-03-04 07:33 UTC, giolekva requested changes

2024-03-04 07:33 UTC, giolekva commented on core/installer/welcome/create-account.html
> +        </div> -->
remove comment

2024-03-04 07:33 UTC, giolekva commented on core/installer/welcome/create-account.html
> +        }
move this to an external css file

2024-03-04 07:33 UTC, giolekva commented on core/installer/welcome/create-account.html
> +				aria-invalid="{{ if .ErrorMessage }}true{{ else }}undefined{{ end }}"
How do you know that the `ErrorMessage` is about the username and not the password? You'll have to differentiate between them

2024-03-06 10:16 UTC, DTabidze commented on core/auth/ui/api.go
> +func handleIdentityCreateError(errResp ErrorResponse) string {
Done

2024-03-06 10:16 UTC, DTabidze commented on core/installer/welcome/create-account.html
> +        </div> -->
Done

2024-03-06 10:16 UTC, DTabidze commented on core/installer/welcome/create-account.html
> +        }
Done. moved to errrors.css

2024-03-06 10:20 UTC, DTabidze commented on core/installer/welcome/create-account.html
> +				aria-invalid="{{ if .ErrorMessage }}true{{ else }}undefined{{ end }}"
If we consider ErrorMessages as a list of objects of type errors, structured like this:

{
  "field": "username",
  "message": "error text"
}
I've implemented HTML to iterate over each object in the list and render the errors in the appropriate place. Should I stick with this HTML-only approach or use JS?

2024-03-06 12:45 UTC, giolekva requested changes

2024-03-06 12:45 UTC, giolekva commented on core/auth/kratos/Makefile
roll back this file

2024-03-06 12:45 UTC, giolekva commented on core/auth/kratos/identity.schema.json
roll back this file

2024-03-06 12:45 UTC, giolekva commented on core/installer/welcome/static/errors.css
This is not styling only errors, I'd name it `main.css`

2024-03-06 12:45 UTC, giolekva commented on core/installer/welcome/static/errors.css
> +}
add empty line at the end of the file

2024-03-06 12:45 UTC, giolekva commented on core/installer/welcome/static/picoOld.min.css
delete this file

2024-03-06 12:45 UTC, giolekva commented on core/installer/welcome/create-account.html
> +				aria-invalid="{{ if .ErrorMessage }}true{{ else }}undefined{{ end }}"
Stick to HTML only version like you have now. But I'd preprocess error messages array in the Go handler first so it is easier to render it here.

Preprocess like: iterate over error messages and group them by field so you get two arrays at the end: `usernameErrors []string` and `passwordErrors []string` and pass them down to the html template

2024-03-06 12:45 UTC, giolekva commented on core/auth/ui/api.go
> +		http.Error(w, errorMessage, http.StatusInternalServerError)
since you updated `create-account.html` to work with array of error messages (instead of doing it in a separate PR), now you'll have to update the api server as well to actually return array instead of string

2024-03-06 16:01 UTC, DTabidze commented on core/installer/welcome/create-account.html
> +				aria-invalid="{{ if .ErrorMessage }}true{{ else }}undefined{{ end }}"
working on it, have not made any changes in HTML yet...

2024-03-06 16:02 UTC, DTabidze commented on core/auth/kratos/Makefile
Done

2024-03-06 16:02 UTC, DTabidze commented on core/auth/kratos/identity.schema.json
Done

2024-03-06 16:04 UTC, DTabidze commented on core/auth/ui/api.go
> +			fmt.Printf("%+v\n", e)
removed

2024-03-07 09:10 UTC, giolekva requested changes

2024-03-07 09:10 UTC, giolekva commented on core/auth/ui/api.go
> +		json.NewEncoder(w).Encode(response)
This might return error: `if err := ....`

2024-03-07 09:10 UTC, giolekva commented on core/auth/ui/api.go
> +func extractErrorMessage(errResp ErrorResponse) string {
This must return `[]ValidationError`

2024-03-07 09:10 UTC, giolekva commented on core/installer/index.html
rollback this file

2024-03-07 09:10 UTC, giolekva commented on core/installer/values-tmpl/core-auth.cue
rollback this file

2024-03-07 09:10 UTC, giolekva commented on core/installer/welcome/create-account.html
> +                {{ if .ErrorMessages.Errors }}
Update this logic to use `.UsernameErrors` and `.PasswordErrors`

2024-03-07 10:39 UTC, DTabidze commented on core/auth/ui/api.go
> +		json.NewEncoder(w).Encode(response)
Fixed

2024-03-07 10:39 UTC, DTabidze commented on core/auth/ui/api.go
> +func extractErrorMessage(errResp ErrorResponse) string {
Fixed

2024-03-07 10:39 UTC, DTabidze commented on core/installer/index.html
Nothing to rollback

2024-03-07 10:40 UTC, DTabidze commented on core/installer/welcome/create-account.html
> +                {{ if .ErrorMessages.Errors }}
Updated

2024-03-07 11:04 UTC, giolekva requested changes

2024-03-07 11:04 UTC, giolekva commented on core/installer/values-tmpl/core-auth.cue
rollback this file

2024-03-07 11:04 UTC, giolekva commented on core/installer/welcome/static/welcome.css
> +}
add new line at the end

2024-03-07 11:05 UTC, DTabidze commented on core/installer/welcome/static/errors.css
> +}
Done

2024-03-07 11:06 UTC, DTabidze commented on core/installer/values-tmpl/core-auth.cue
Done

2024-03-07 11:07 UTC, DTabidze commented on core/auth/ui/api.go
> +	// TODO Handle kratos respones
Done

2024-03-07 11:12 UTC, DTabidze commented on core/auth/ui/api.go
> +			return
Fixed

2024-03-07 11:12 UTC, DTabidze commented on core/installer/welcome/static/welcome.css
> +}
Done

2024-03-08 08:53 UTC, giolekva approved these changes

2024-03-08 08:53 UTC, merged