Groups and  memberships.
giolekva/pcloud pull request #97
Opened 2024-03-14 13:49 UTC by DTabidze

2024-03-14 14:06 UTC, giolekva commented on core/auth/memberships/Dockerfile
> +RUN chmod +x /usr/bin/memberships
add empty line at the end

2024-03-14 14:06 UTC, giolekva commented on core/auth/memberships/main.go
> +type Store interface {
I'd move this interface definition as one of the first things in the file

2024-03-14 14:06 UTC, giolekva commented on core/auth/memberships/main.go
> +        CREATE TABLE IF NOT EXISTS user_membership (
If table above is called `group_to_group` I'd call this `user_to_group`

2024-03-14 14:06 UTC, giolekva commented on core/auth/memberships/main.go
> +	}
Since we are using relational db we should setup unique constraint on group name. So that if someone (developer, one of us) tries to manually mutate data in the db we don't accidentally repeat already used name.

2024-03-14 14:06 UTC, giolekva commented on core/auth/memberships/main.go
> +	// TODO dtabidze
`// TODO(dtabidze): should check ...`

2024-03-14 14:17 UTC, DTabidze commented on core/auth/memberships/Dockerfile
> +RUN chmod +x /usr/bin/memberships
Done

2024-03-14 14:18 UTC, DTabidze commented on core/auth/memberships/main.go
> +type Store interface {
Done

2024-03-14 15:16 UTC, DTabidze commented on core/auth/memberships/main.go
> +	}
Checked the error.go file in the go-sqlite3 library and found the definition for ErrConstraint as ErrNo(19), indicating an abort due to constraint violation. With this insight, I revised my code. As a primary key is inherently unique, SQLite will automatically detect unique constraint violations upon insertion.  haven't tested it yet.

https://github.com/mattn/go-sqlite3/blob/master/error.go

2024-03-15 06:02 UTC, giolekva commented on core/auth/memberships/main.go
>  var indexHTML embed.FS
You can give `string` or `[]byte` type to `indexHTML` and `addUser` variables and Go will automatically read those files, so that you don't have to call `addUsaer.ReadFile("...")` below.

2024-03-15 06:02 UTC, giolekva commented on core/auth/memberships/main.go
> +var addUser embed.FS
Rename to `groupHTML`

2024-03-15 06:56 UTC, giolekva commented on core/auth/memberships/static/main.js
> +  });
Why do you need this at all? Why not just use a link and go to the `/group/<NAME>` page?

2024-03-15 07:03 UTC, giolekva requested changes

2024-03-15 07:03 UTC, giolekva commented on core/auth/memberships/group.html
> +    <title>URL Shortener</title>
change title

2024-03-15 07:03 UTC, giolekva commented on core/auth/memberships/index.html
> +    <title>URL Shortener</title>
change title

2024-03-15 13:16 UTC, DTabidze commented on core/auth/memberships/main.go
> +		// }
Yes. I will remove all unnecessary comments at the end.

2024-03-15 13:21 UTC, DTabidze commented on core/auth/memberships/index.html
> +            <td><a href="/group/{{ .Group.Name }}" class="group-link">{{ .Group.Name }}</a></td>
Not in any CSS file. I just use it in main.js script to grab all Groups and attach Event listener to em. Should I do anything else?

2024-03-15 13:23 UTC, DTabidze commented on core/auth/memberships/main.go
> +	CreateGroup(loggedInUsername string, group Group) error
Done

2024-03-15 13:27 UTC, giolekva commented on core/auth/memberships/index.html
> +            <td><a href="/group/{{ .Group.Name }}" class="group-link">{{ .Group.Name }}</a></td>
See other comment on the js part, there is no need for javascript at all

2024-03-15 13:27 UTC, DTabidze commented on core/auth/memberships/main.go
> +	GetOwnerUsers(groupname string) ([]string, error)
Done

2024-03-15 13:28 UTC, DTabidze commented on core/auth/memberships/main.go
> +	GetMembershipUsers(groupname string) ([]string, error)
Done

2024-03-15 13:31 UTC, DTabidze commented on core/auth/memberships/main.go
> +	AddUserIntoGroup(loggedInUsername, targetUsername, groupName string, status string) error
Done

2024-03-15 13:32 UTC, DTabidze commented on core/auth/memberships/main.go
> +var addUser embed.FS
Done

2024-03-15 13:33 UTC, DTabidze commented on core/auth/memberships/group.html
> +    <title>URL Shortener</title>
Oops. Done

2024-03-15 13:34 UTC, DTabidze commented on core/auth/memberships/index.html
> +    <title>URL Shortener</title>
Oops x2. Done

2024-03-15 13:40 UTC, DTabidze commented on core/auth/memberships/static/main.js
> +  });
Done. So no need to user main.js yet. I will let this file stay here, might have to use it later when changing membership and etc.

2024-03-15 15:13 UTC, DTabidze commented on core/auth/memberships/main.go
>  	}
made a func to check if user is owner of that group, using simple select.
moved permission check into handler.

2024-03-15 15:13 UTC, DTabidze commented on core/auth/memberships/static/main.js
> +  });
Removed main.js

2024-03-15 15:13 UTC, DTabidze commented on core/auth/memberships/main.go
>  var indexHTML embed.FS
Done

2024-03-18 08:14 UTC, giolekva reviewed
Minor comments, will do full logic review now

2024-03-18 08:14 UTC, giolekva commented on core/auth/memberships/main.go
> +	tmpl, err := template.New("index").Parse(string(indexHtml))
if template `Parse` method requires string, I'd give `indexHTML` and `groupHTML` variables string type

2024-03-18 08:14 UTC, giolekva commented on core/auth/memberships/main.go
> +var groupHTML []byte
Names these variables consistently, either make `HTML` all uppercase in both cases or not

2024-03-18 08:14 UTC, giolekva commented on core/auth/memberships/main.go
> +	GetGroupMembers(groupname string) ([]string, error)
Give variables consistent names here and across all files, either use `groupName` or `groupname`.

Actually I'd simplify naming even more, I'd use just `group` and `user` (instead of `username`, `targetUsername` and `owner`

2024-03-18 08:14 UTC, giolekva commented on core/auth/memberships/main.go
> +    `
Fix indentation, I'd move this on previous line

2024-03-18 10:35 UTC, giolekva requested changes
Overall looks good, I left comments mostly regarding code organisation and improving code quality.

2024-03-18 10:35 UTC, giolekva commented on core/auth/memberships/main.go
> +    `)
fix indentation

2024-03-18 10:35 UTC, giolekva commented on core/auth/memberships/main.go
> +
remove unnecessary empty lines, here and across whole file

2024-03-18 10:35 UTC, giolekva commented on core/auth/memberships/main.go
> +    `
fix indentation

2024-03-18 10:35 UTC, giolekva commented on core/auth/memberships/main.go
> +	}
What if user is both owner and a member of the same group? Will not this render the same group twice on the UI?

2024-03-18 10:35 UTC, giolekva commented on core/auth/memberships/main.go
> +func (s *Server) handler(w http.ResponseWriter, r *http.Request) {
Give this method a better name, maybe `homePageHandler` ?

2024-03-18 10:35 UTC, giolekva commented on core/auth/memberships/main.go
> +func renderHTML(w http.ResponseWriter, r *http.Request, tmpl *template.Template, data interface{}) {
Is this helper function needed? It is being used only in one place.

Also `r` argument can be removed, it is not used anywhere.

2024-03-18 10:35 UTC, giolekva commented on core/auth/memberships/main.go
> +}
Move this above `NewSQLiteStore` function

2024-03-18 10:35 UTC, giolekva commented on core/auth/memberships/main.go
> +        SELECT groups.name, groups.description
Remove whitespaces at the end of the lines, here and everywhere across all files.

You might want to configure code editor (vscode) so it highlights extra whitespaces so that they are visible and eye catching.

2024-03-18 10:35 UTC, giolekva commented on core/auth/memberships/main.go
> +	_, err = s.db.Exec(query, username, group.Name)
These two queries must run inside a single transaction. Without that there is a chance that first query runs successfully and second one files, in which case we will end up with new group without any owners set to it.

While if you run those in transaction and any query fails, other already executed queries will be rolled back.

2024-03-18 10:35 UTC, giolekva commented on core/auth/memberships/main.go
> +func userExistsInTable(db *sql.DB, tableName, username, groupName string) (bool, error) {
Make this method of the `SqliteStore` struct so you don't have to pass `db` as an argument.

I'd also rename to `useGroupPairExists`

2024-03-18 10:35 UTC, giolekva commented on core/auth/memberships/main.go
> +	query := fmt.Sprintf("SELECT username FROM %s WHERE username = ? AND group_name = ?", tableName)
Can you use `SELECT EXISTS` here?

2024-03-18 10:35 UTC, giolekva commented on core/auth/memberships/main.go
> +	_, err = s.db.Exec(`INSERT INTO user_to_group (username, group_name) VALUES (?, ?)`, targetUsername, groupName)
You need to run `userExists...` and this query in a single transaction as well.

2024-03-18 10:35 UTC, giolekva commented on core/auth/memberships/index.html
> +    <form action="/" method="post">
Use different path for group creation, like `action="/create-group"`

2024-03-18 10:35 UTC, giolekva commented on core/auth/memberships/main.go
> +func (s *SQLiteStore) getUsersByGroup(table, groupname string) ([]string, error) {
Move `SQLiteStore` methods after `SQLiteStore` struct definition, they should be grouped together.

2024-03-18 10:35 UTC, giolekva commented on core/auth/memberships/main.go
> +		MembershipUsers []string
I'd rename these to just `Owners` and `Members`

2024-03-18 10:47 UTC, DTabidze commented on core/auth/memberships/main.go
> +	tmpl, err := template.New("index").Parse(string(indexHtml))
Done.

2024-03-18 10:47 UTC, DTabidze commented on core/auth/memberships/main.go
> +    `
Done

2024-03-18 10:47 UTC, DTabidze commented on core/auth/memberships/main.go
> +	GetGroupMembers(groupname string) ([]string, error)
Fixed.

2024-03-18 17:55 UTC, giolekva commented on core/auth/memberships/static/group.css
rename to main.css

2024-03-18 17:55 UTC, giolekva commented on core/auth/memberships/static/group.css
> +.description {
add empty line before this

2024-03-18 17:55 UTC, giolekva commented on core/auth/memberships/static/group.css
> +.divider {
add empty line before this

2024-03-18 17:55 UTC, giolekva commented on core/auth/memberships/main.go
> +	userGroupPairExists(table, user, group string) (bool, error)
This is internal implementation detail of the `SQLiteStore` and should not be part of the interface

2024-03-18 17:55 UTC, giolekva commented on core/auth/memberships/main.go
> +	GetGroupDescription(groupName string) (string, error)
groupName -> group

2024-03-18 21:36 UTC, DTabidze commented on core/auth/memberships/static/group.css
Done.

2024-03-18 21:36 UTC, DTabidze commented on core/auth/memberships/static/group.css
> +.description {
Done.

2024-03-18 21:36 UTC, DTabidze commented on core/auth/memberships/static/group.css
> +.divider {
Done.

2024-03-18 21:36 UTC, DTabidze commented on core/auth/memberships/main.go
> +	GetGroupDescription(groupName string) (string, error)
Done.

2024-03-18 21:36 UTC, DTabidze commented on core/auth/memberships/main.go
> +	userGroupPairExists(table, user, group string) (bool, error)
Done.

2024-03-19 07:08 UTC, giolekva requested changes
Overall looks great, again minor comments mostly.

You have few comments from previous round unaddressed.

2024-03-19 07:08 UTC, giolekva commented on core/auth/memberships/group.html
> +    </form>
rm whitespaces at the end

2024-03-19 07:08 UTC, giolekva commented on core/auth/memberships/main.go
> +	_, err := getLoggedInUser(r)
You need to check ownership here as well.

2024-03-19 07:08 UTC, giolekva commented on core/auth/memberships/main.go
> +		return
Move this into it's own handler

2024-03-19 11:49 UTC, DTabidze commented on core/auth/memberships/main.go
> +	_, err := getLoggedInUser(r)
Done.

2024-03-19 11:49 UTC, DTabidze commented on core/auth/memberships/main.go
> +	if err != nil {
Done.

2024-03-19 11:49 UTC, DTabidze commented on core/installer/values-tmpl/memberships.cue
Done.

2024-03-19 11:49 UTC, DTabidze commented on core/installer/values-tmpl/memberships.cue
> +icon: "<svg xmlns='http://www.w3.org/2000/svg" width="40.63" height="50" viewBox="0 0 13 16"><circle cx="2" cy="10" r="1" fill="currentColor"/><circle cx="2" cy="6" r="1" fill="currentColor"/><path f
Done.

2024-03-19 11:49 UTC, DTabidze commented on core/installer/values-tmpl/memberships.cue
> +			}
Done.

2024-03-19 12:24 UTC, giolekva commented on core/installer/values-tmpl/memberships.cue
> +icon: "<svg xmlns='http://www.w3.org/2000/svg" width="50" height="50" viewBox="0 0 24 24"><path fill="currentColor" d="M15.43 15.48c-1.1-.49-2.26-.73-3.43-.73c-1.18 0-2.33.25-3.43.73c-.23.1-.4.29-.49
You need to fix quotes here

2024-03-19 12:32 UTC, DTabidze commented on core/auth/memberships/main.go
> +	_, err = s.db.Exec(`INSERT INTO user_to_group (username, group_name) VALUES (?, ?)`, targetUsername, groupName)
Done.

2024-03-19 12:40 UTC, DTabidze commented on core/auth/memberships/main.go
> +var groupHTML []byte
Done.

2024-03-19 12:59 UTC, giolekva requested changes

2024-03-19 12:59 UTC, giolekva commented on core/auth/memberships/main.go
> +	if _, err = s.db.Exec(`INSERT INTO owners (username, group_name) VALUES (?, ?)`, user, group); err != nil {
This must run in the `tx` as well

2024-03-19 12:59 UTC, giolekva commented on core/auth/memberships/main.go
>  func (s *SQLiteStore) parentChildGroupPairExists(parent, child string) (bool, error) {
Like when checking for user, group pair this must happen in transaction as well.

2024-03-19 12:59 UTC, giolekva commented on core/auth/memberships/main.go
> +	defer tx.Rollback()
This rollback should happen only in case of an error and not when Commit succeeds. Right now it is always executed no matter success/failure of the function.
Manually invoke `tx.Rollback()` right before `return err`-s.

Here and in another functions using tx as well.

2024-03-19 13:16 UTC, DTabidze commented on core/auth/memberships/main.go
>  func (s *SQLiteStore) parentChildGroupPairExists(parent, child string) (bool, error) {
Done.

2024-03-19 13:18 UTC, DTabidze commented on core/auth/memberships/main.go
> +	defer tx.Rollback()
Done.

2024-03-19 13:20 UTC, giolekva approved these changes

2024-03-19 13:20 UTC, giolekva commented on core/auth/memberships/main.go
> +		// }
Can they be remvoed now?

2024-03-19 13:20 UTC, giolekva commented on core/auth/memberships/main.go
> +	_, err = s.db.Exec(query, username, group.Name)
ping

2024-03-19 13:20 UTC, giolekva commented on core/auth/memberships/main.go
> +	http.HandleFunc("/addchildgroup", s.addChildGroupHandler)
Give these handlers consistent urls:
`/create-group /add-user /add-child-group`

2024-03-19 13:20 UTC, DTabidze commented on core/auth/memberships/main.go
> +	if _, err = s.db.Exec(`INSERT INTO owners (username, group_name) VALUES (?, ?)`, user, group); err != nil {
Done.

2024-03-19 13:22 UTC, DTabidze commented on core/auth/memberships/main.go
> +		// }
ok

2024-03-19 13:25 UTC, DTabidze commented on core/auth/memberships/main.go
> +	http.HandleFunc("/addchildgroup", s.addChildGroupHandler)
Done.

2024-03-19 13:29 UTC, DTabidze commented on core/auth/memberships/main.go
> +	_, err = s.db.Exec(query, username, group.Name)
Done.

2024-03-19 13:42 UTC, merged